### ISSUE TITLE
Sign Formatting set to default?

### ISSUE THREAD

**Issue by KhaarNaj** [Randude14/LotteryPlus#25]
So here is what I wrote down:

sign-formats:

```
# this format is used when the lottery is running and is doing a time update
Update:
    line-2: '<reward>'
    line-3: '<time>'
    line-4: '<ticketcost>'
```

But, in game, the sign is still by default, like: name - time - reward.

Any idea?

Thx for back.
